import { Permission, PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  MANAGER: [
    PERMISSIONS.USERS_VIEW,

    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CUSTOMERS_DELETE,

    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_APPROVE,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_ORDER,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_SCHEDULE,
  ],

  SERVICE_ADVISOR: [
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,

    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_CREATE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  TECHNICIAN: [
    PERMISSIONS.CUSTOMERS_READ,

    PERMISSIONS.INVENTORY_READ,

    PERMISSIONS.REPORTS_VIEW,
  ],

  ACCOUNTANT: [
    PERMISSIONS.CUSTOMERS_READ,

    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_CREATE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  PARTS_MANAGER: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_ORDER,
    PERMISSIONS.INVENTORY_AUDIT,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
};